package interfazGrafica;

import java.text.DateFormat;
import java.text.SimpleDateFormat;
import javax.swing.UnsupportedLookAndFeelException;
import terapeuta.Reporte;
import interfazDeConexion.AccesoReporte;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

public class VentanaReporte extends javax.swing.JFrame {

    /**
     * Creates new form Terapeuta
     */
    AccesoReporte accesoReporte = new AccesoReporte();
    public VentanaReporte() {
        initComponents();
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        this.setTitle("Nueva sesión.");
        this.setIconImage((new ImageIcon(getClass().getResource("/imagenes/icono.jpg")).getImage()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        acuerdos = new javax.swing.JTextArea();
        jScrollPane1 = new javax.swing.JScrollPane();
        avances = new javax.swing.JTextArea();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        ap = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        des = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        guardar = new javax.swing.JButton();
        id_expediente = new javax.swing.JSpinner();
        tser = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/report.png"))); // NOI18N

        jLabel8.setFont(new java.awt.Font("EngraversGothic BT", 0, 18)); // NOI18N
        jLabel8.setText("Desarrollo");

        jLabel9.setFont(new java.awt.Font("EngraversGothic BT", 0, 18)); // NOI18N
        jLabel9.setText("Acuerdos");

        acuerdos.setColumns(20);
        acuerdos.setFont(new java.awt.Font("EngraversGothic BT", 0, 18)); // NOI18N
        acuerdos.setRows(5);
        jScrollPane4.setViewportView(acuerdos);

        avances.setColumns(20);
        avances.setFont(new java.awt.Font("EngraversGothic BT", 0, 18)); // NOI18N
        avances.setRows(5);
        jScrollPane1.setViewportView(avances);

        jLabel10.setFont(new java.awt.Font("EngraversGothic BT", 0, 18)); // NOI18N
        jLabel10.setText("Avances/nivel de avance del paciente  (1-10)");

        ap.setColumns(20);
        ap.setFont(new java.awt.Font("EngraversGothic BT", 0, 18)); // NOI18N
        ap.setRows(5);
        jScrollPane2.setViewportView(ap);

        jLabel2.setFont(new java.awt.Font("EngraversGothic BT", 0, 18)); // NOI18N
        jLabel2.setText("Numero de Expediente");

        des.setColumns(20);
        des.setFont(new java.awt.Font("EngraversGothic BT", 0, 18)); // NOI18N
        des.setRows(5);
        jScrollPane3.setViewportView(des);

        jLabel4.setFont(new java.awt.Font("EngraversGothic BT", 0, 18)); // NOI18N
        jLabel4.setText("Tipo de servicio");

        jLabel7.setFont(new java.awt.Font("EngraversGothic BT", 0, 18)); // NOI18N
        jLabel7.setText("Apertura");

        guardar.setFont(new java.awt.Font("EngraversGothic BT", 0, 18)); // NOI18N
        guardar.setText("Guardar");
        guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarActionPerformed(evt);
            }
        });

        id_expediente.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        tser.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tser.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Psicología", "Psiquiatría", "Nutrición", "Neurología", "Atención espiritual", "Asesoría legal" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(guardar)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel10)
                            .addComponent(jScrollPane2)
                            .addComponent(jScrollPane3)
                            .addComponent(jScrollPane4)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 873, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tser, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(id_expediente, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel2)
                    .addComponent(id_expediente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(guardar)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Agrega un nuevo reporte a la base de datos o muestra un mensaje de error al fallar la operación
    private void guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarActionPerformed
        try {                                        
            if((Integer)id_expediente.getValue() < 1){
                JOptionPane.showMessageDialog(null, "Revise el valor del expediente.", "Error de datos.", JOptionPane.WARNING_MESSAGE);
                return;
            }
            if(((String)tser.getSelectedItem()).isEmpty()){
                JOptionPane.showMessageDialog(null, "Especifique el tipo de servicio ofrecido.");
                return;
            }
            if(!accesoReporte.expedienteAsignado(accesoReporte.obtenerIdentificadorDeTerapeuta(InicioSesion.identificadorUsuario), (Integer)this.id_expediente.getValue())){
                JOptionPane.showMessageDialog(null, "No se puede obtener acceso a ese paciente.");
                return;
            }
            try {
                Reporte aGuardar = guardarReporte();
                accesoReporte.agregarReporte(aGuardar);
                JOptionPane.showMessageDialog(this, "Reporte #" + aGuardar.getNumSesion() +" del paciente guardado correctamente.");
                this.dispose();
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(VentanaReporte.class.getName()).log(Level.SEVERE, null, ex);
            } catch(Exception e) {
                JOptionPane.showMessageDialog(this, "Error al guardar el reporte, favor de revisar los campos.");
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(VentanaReporte.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_guardarActionPerformed

    //Inicializa al valor vacío todos los campos de la ventana
    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        this.acuerdos.setText(null);
        this.ap.setText(null);
        this.avances.setText(null);
        this.des.setText(null);
        this.id_expediente.setValue(0);
        this.tser.setSelectedIndex(0);
    }//GEN-LAST:event_formWindowClosed

    /**
     * @param args the command line arguments
     */
    
    //Agrega un nuevo reporte a la base de datos o muestra un mensaje de error al fallar la operación
    private Reporte guardarReporte() throws ClassNotFoundException {
        DateFormat formatoFecha = new SimpleDateFormat("yyyy-MM-dd");
        java.util.Date fecha = new java.util.Date();
        Reporte reporte = new Reporte();
        try { 
            AccesoReporte acceso = new AccesoReporte();
            //reporte.setIdentificadorPersona(Integer.valueOf(this.id_expediente.getText()));
            reporte.ingresarNumExpediente((Integer)id_expediente.getValue());
            reporte.ingresarNumSesion(acceso.siguienteSesion(reporte.getNumExpediente()));
            reporte.ingresarTipoDeServicio(((String)this.tser.getSelectedItem()).trim().toUpperCase());
            reporte.ingresarCita(java.sql.Date.valueOf(formatoFecha.format(fecha)));
            reporte.ingresarApertura(this.ap.getText());
            reporte.ingresarDesarrollo(this.des.getText());
            reporte.ingresarAcuerdos(this.acuerdos.getText());
            reporte.ingresarAvances(this.avances.getText());
            reporte.ingresarProximaCita(java.sql.Date.valueOf(formatoFecha.format(fecha)));
        } catch(Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Ingresa únicamente números en los campos numero expediente, numero sesion y id expediente");
        }
        return reporte;
    }
    
    public static void main(String args[]) throws InstantiationException, IllegalAccessException, UnsupportedLookAndFeelException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            //java.util.logging.Logger.getLogger(Terapeuta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } /*catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Terapeuta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Terapeuta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Terapeuta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }*/
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea acuerdos;
    private javax.swing.JTextArea ap;
    private javax.swing.JTextArea avances;
    private javax.swing.JTextArea des;
    private javax.swing.JButton guardar;
    private javax.swing.JSpinner id_expediente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JComboBox<String> tser;
    // End of variables declaration//GEN-END:variables
}
